apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        test: "v9"
        prometheus.io/scrape: "false"
    spec:
      containers:
      - name: nginx
        image: nginx:1.17
        imagePullPolicy: IfNotPresent
        env:
          - name: TEST
            value: "v7"
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 20m
